### ISSUE TITLE
DMG performance on GBS 4.0 with Platformer+ slow movement running on ground (not in air)

### ISSUE THREAD

**Issue by joeledge** [becomingplural/GBS_PlatformerPlus#20]
I tested GBS v3.2 (with slopes) and Platformer+ on DMG and it ran fine.

I've just tried GBS 4 and Platformer+ on DMG and it's very slow when running on the ground on DMG (then runs faster when jumping in the air) but if I remove the Platformer+ plugin, it runs smoothly again.

https://github.com/becomingplural/GBS_PlatformerPlus/assets/28432913/70d78804-54d5-4a1f-99a9-a3f8c0474ace

https://github.com/becomingplural/GBS_PlatformerPlus/assets/28432913/c01a27fe-7a9a-41f2-b125-3d44eae92dcc

**Comment by maxoakland** [comment]
Can you put some extra actors in the scene to test if the slowness is affecting them too?

**Comment by becomingplural** [comment]
This looks like a larger GBStudio issue. I just added an issue on that GitHub
